### ISSUE TITLE
add option to stop superplaceholder at any time

### ISSUE THREAD

**Issue by chinchang** [chinchang/superplaceholder.js#11]

**Comment by work-bition** [comment]
What time can you realize it?

**Comment by chinchang** [comment]
I'll try to get this implemented this weekend.

**Comment by work-bition** [comment]
Thank you very much. I am looking forward to seeing it!

**Comment by chinchang** [comment]
@work-bition By default superplaceholder starts playing when you focus an input. Let's say you stop it with the new interface. Now when you focus that input, what do you expect - Should superplaceholder again start playing or not?

**Comment by chinchang** [comment]
PR -> #19

**Comment by chinchang** [comment]
This is live in 1.0.0
