### ISSUE TITLE
placeholder="null" after input's blur

### ISSUE THREAD

**Issue by asparkam** [chinchang/superplaceholder.js#14]
Placeholder text is not disappearing and it's value="null" string. Can you set placeholder to empty string? Also will be helpful options like: showOnlyOnFocus or hideOnBlur

Chrome: 62.0.3202.94
Using enviroment: react es6 import
Screenshots:
![2018-03-27_141507](https://user-images.githubusercontent.com/30487905/37952489-1a56e92e-31ca-11e8-910d-c54f38d9906b.png)

![2018-03-27_141448](https://user-images.githubusercontent.com/30487905/37952477-0e13b82c-31ca-11e8-9224-f74a58521eee.png)

**Comment by asparkam** [comment]
Problem is here: https://github.com/chinchang/superplaceholder.js/blob/master/src/superplaceholder.js#L66
Then I hasn't original placeholder. Must be something like this:
`this.el.setAttribute('placeholder', this.originalPlaceholder ? this.originalPlaceholder : '');`

**Comment by chinchang** [comment]
Hi @asparkam. The issue is fixed and live in 0.1.2. Thanks for reporting.
