### ISSUE TITLE
Importing in Svelte

### ISSUE THREAD

**Issue by Cranbaerry** [chinchang/superplaceholder.js#26]
I'm having trouble importing this library to svelte
Here's the code that I used

```
import superplaceholder from 'superplaceholder';
superplaceholder({
		el: document.querySelector('input'),
		sentences: ['Something to show', 'Another thing to show']
	});
```

The error is 

`Cannot find module 'superplaceholder' imported from 'D:/Documents/Svelte/aol/src/routes/+page.svelte'`

How do I import this library?

**Comment by chinchang** [comment]
This is because superplaceholder doens't export anything. You can import it without expecting out of it and then use `window.superplaceholder` instead:

```
import 'superplaceholder';
window.superplaceholder({
		el: document.querySelector('input'),
		sentences: ['Something to show', 'Another thing to show']
	});
```
