### ISSUE TITLE
Can we deprecate `document.querySelector()`?

### ISSUE THREAD

**Issue by mayeenulislam** [chinchang/superplaceholder.js#9]
Any jQuery plugin in now-a-days are smart enough selecting elements, and chaining functions. i.e.:

```
var foo_field = $('#foo-elem');
foo_field.pluginFunc().pluginFunc2({
    param: val,
});
```

And we can check the availability of that selector also:

```
if(foo_field.length > 0) {
    //call the plugin functionality
}
```

But for this plugin I'm having issues with: `el: document.querySelector('#foo-elem'),`

It's making redundancy and repeating in selecting DOM elements.

**Comment by chinchang** [comment]
@mayeenulislam Actually this isn't a jQuery plugin. Its a plain JavaScript library. Also you continue using your `$` variable to fetch elements and check lengths and all, like so:

```
if ($('.some-class').length) {
 superplaceholder({
  el: $('.some-class').get(0),
  sentences: []
 });
}
```
